# Generated by Django 3.2.9 on 2021-11-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_appperformance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appperformance',
            name='revenue',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
        migrations.AlterField(
            model_name='appperformance',
            name='spend',
            field=models.DecimalField(decimal_places=8, max_digits=11),
        ),
    ]
