# Generated by Django 3.2.9 on 2021-11-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_auto_20211106_2310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appperformance',
            old_name='impression',
            new_name='impressions',
        ),
    ]
